# Generated by Django 5.2.17 on 2026-08-29 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='What the student is called in lessons. A first name is enough.', max_length=60)),
                ('platform', models.CharField(choices=[('fiverr', 'Fiverr'), ('preply', 'Preply'), ('direct', 'Direct / Zoom')], default='direct', max_length=20)),
                ('is_minor', models.BooleanField(default=False, help_text='Tick if under 18. Guardian contact is then required.')),
                ('guardian_email', models.EmailField(blank=True, help_text='Only for students under 18. Leave empty otherwise.', max_length=254)),
                ('notes', models.TextField(blank=True, help_text='Teaching notes only. Do not store anything sensitive here.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
    ]
