# Generated by Django 5.2.17 on 2026-09-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archived students are hidden from the active roster.'),
        ),
    ]
