# Generated by Django 5.2.17 on 2026-09-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='theme_palette',
            field=models.CharField(blank=True, help_text="Key of the student's chosen site color palette. Blank means the default theme.", max_length=32),
        ),
    ]
