# Generated by Django 5.2.17 on 2026-08-29 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-date', 'order', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lesson',
            name='date',
            field=models.DateField(blank=True, help_text="Orders this on the student's timeline.", null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='hint_seconds_default',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='lesson',
            name='markdown_source',
            field=models.TextField(blank=True, help_text='The lesson document. See skills/FORMAT_SPEC.md.'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='meta',
            field=models.JSONField(blank=True, default=dict, help_text='Unknown front-matter keys, rendered as header pills.'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='student',
            field=models.ForeignKey(blank=True, help_text='Set for a dated document written for one student.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_lessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lesson',
            name='theme',
            field=models.CharField(blank=True, choices=[('kids', 'Kids'), ('beginner', 'Beginner'), ('professional', 'Professional')], help_text='Blank uses the beginner theme.', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, help_text='What the student will do this session. (Legacy field — new lessons use markdown_source.)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Locked (unticked) lessons are invisible to the student.'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Position in the course (shared curriculum lessons only).'),
        ),
        migrations.CreateModel(
            name='HintReveal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=64)),
                ('revealed_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hint_reveals', to='learning.lesson')),
            ],
            options={
                'ordering': ['revealed_at'],
            },
        ),
        migrations.CreateModel(
            name='BlankAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blank_id', models.CharField(max_length=64)),
                ('value', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blank_answers', to='learning.lesson')),
            ],
            options={
                'unique_together': {('lesson', 'blank_id')},
            },
        ),
        migrations.CreateModel(
            name='ChecklistCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_id', models.CharField(max_length=32)),
                ('is_checked', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_checks', to='learning.lesson')),
            ],
            options={
                'unique_together': {('lesson', 'check_id')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[('code', 'Code'), ('choice', 'Choice'), ('step', 'Step'), ('answer', 'Answer')], default='code', max_length=20)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_orphaned', models.BooleanField(default=False, help_text='No longer in the markdown source.')),
                ('is_complete', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='learning.lesson')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('lesson', 'task_id')},
            },
        ),
    ]
