# Generated by Django 5.2.17 on 2026-08-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_lesson_options_alter_lesson_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='hint_seconds_default',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
