# Generated by Django 5.2.17 on 2026-08-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_alter_lesson_hint_seconds_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='theme',
        ),
        migrations.AddField(
            model_name='lesson',
            name='format',
            field=models.CharField(blank=True, choices=[('document', 'Document / project'), ('slide', 'Slide')], help_text='Blank uses the document/project format.', max_length=20),
        ),
    ]
