# Generated by Django 5.2.17 on 2026-08-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_remove_lesson_theme_lesson_format'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checklistcheck',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='checklistcheck',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='format',
        ),
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='hint_seconds_default',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.DeleteModel(
            name='BlankAnswer',
        ),
        migrations.DeleteModel(
            name='ChecklistCheck',
        ),
    ]
