# Generated by Django 5.2.17 on 2026-09-07 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_alter_checklistcheck_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guidelines', models.TextField(blank=True, help_text='What this homework should cover (your brief to yourself).')),
                ('content', models.TextField(help_text='The homework itself, as given to the student.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_set', to='learning.lesson')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
