# Generated by Django 5.2.17 on 2026-09-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Tutor has checked this step. The next step stays locked until then.'),
        ),
    ]
