# Generated by Django 5.2.17 on 2026-09-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_task_approved_at_task_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='mode',
            field=models.CharField(choices=[('with_tutor', 'With tutor — next step waits for your approval'), ('solo', 'Student does this alone — unlocks the next step by itself')], default='with_tutor', max_length=10),
        ),
    ]
