# Generated by Django 5.2.17 on 2026-09-14 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_task_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='task',
            name='mode',
        ),
    ]
