# Generated by Django 5.2.17 on 2026-09-14 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_remove_task_approved_at_remove_task_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_published',
        ),
    ]
