# Generated by Django 5.2.17 on 2026-09-14 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_remove_lesson_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='hint_seconds_default',
        ),
    ]
