# Generated by Django 5.2.17 on 2026-09-23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0014_quizattempt"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="quizattempt",
            unique_together=set(),
        ),
    ]