# Generated by Django 5.2.17 on 2026-09-02 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('summary', models.CharField(blank=True, help_text="Short blurb shown on cards and used as the page's meta description.", max_length=300)),
                ('body', models.TextField(blank=True, help_text='Article content, written in Markdown.')),
                ('order', models.PositiveIntegerField(default=1, help_text='Position within its domain.')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide from the public site.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='tutorials.domain')),
            ],
            options={
                'ordering': ['domain__name', 'order', 'title'],
            },
        ),
    ]
